### ISSUE TITLE
Hello ! Anybody here...

### ISSUE THREAD

**Issue by kskarthik** [kaios/kaios#1]
I am curious to know more about this project ! you powering the jiophone right?

**Comment by kaios** [comment]
No, this is not the same OS that is on your phone. The KaiOS, which is a forked version of Firefox OS, is the version that runs on your phone. This project is completely different and has no affiliation with the other project. My project started in 2014 as a micro Linux distro running on x86 platforms. The other version is a mobile phone distro for ARM processors.

**Comment by kskarthik** [comment]
Oh... https://kaiostech.com is your new website ?

**Comment by kaios** [comment]
No. KaiOS a small x86 based 15 mb OS that does not run on ARM. The KaiOS
you are emailing me about is a fork of Firefox OS. Nothing to do with my OS
other than the fact they copied my name since I been around 2014.

**Comment by kskarthik** [comment]
Oh.. They stole your name. Thanks for your replies & Sorry for disturbing you.
