### ISSUE TITLE
tethering

### ISSUE THREAD

**Issue by nikhilbendre12** [kaios/kaios#3]
USB TETHERING is most important thing on kaios so i want to program for it...
it is possible or not???

**Comment by kaios** [comment]
This is not the phone KaiOS. That is a completely different project using different sources. This is the original KaiOS distro that has nothing to do with the phone OS.

**Comment by nikhilbendre12** [comment]
In that official side they told to develop the application for kaios
Here the link of official kaios -

https://medium.com/@kaiostech

And the using third party or the other sources we can introduce the
tethering in that device??

What is requirements for tethering (it work on only using software or it
must required any type of hardware part also )??

**Comment by kaios** [comment]
Again, that is KaiOS Technologies. This project has zero affiliation with them. This is an open source distribution for X86 hardware. What you are referring to is a phone based OS. There is no USB tethering needed for this project as it has USB drivers built into the kernel.

**Comment by nikhilbendre12** [comment]
Build into kernel we can use it

**Comment by kaios** [comment]
You are not understanding what I am saying. KaiOS Technologies does not use any of this source code or kernel. This is a completely different project and has nothing to do with any phones. This distro cannot even run on non X86 hardware, that phone is either a MIPS or an ARM, neither of which are not Intel/AMD based x86 hardware. This project cannot help you as it has nothing to do with the phone. How can you not understand this? Contact KaiOS Technologies if you want their source code. This project is not that!
